apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
spec:
  secretName: etcd-peer-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - redhat
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - etcd-0.etcd
    - etcd-1.etcd
    - etcd-2.etcd
    - etcd-0
    - etcd-1
    - etcd-2
  ipAddresses:
    - 0.0.0.0
  issuerRef:
    name: kcp
