apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kcp
spec:
  secretName: kcp-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - redhat
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - kcp
    - "*openshiftapps.com"
  ipAddresses:
    - 0.0.0.0
  issuerRef:
    name: kcp
