---
apiVersion: v1
kind: Service
metadata:
  name: kcp
spec:
  ports:
    - protocol: TCP
      name: https
      port: 6443
      targetPort: 6443
  selector:
    app: kcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcp
  labels:
    app: kcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcp
  template:
    metadata:
      labels:
        app: kcp
    spec:
      containers:
      - name: kcp
        image: quay.io/klape/kcp:latest
        ports:
        - containerPort: 6443
        command:
          - /kcp-config
          - /etc/kcp/config/kcp.yaml
          - /kcp
          - start
        volumeMounts:
          - name: etcd-certs
            mountPath: /etc/etcd/tls/server
          - name: kcp-certs
            mountPath: /etc/kcp/tls/server
          - name: kcp-config
            mountPath: /etc/kcp/config
      volumes:
      - name: etcd-certs
        secret:
          secretName: etcd-secret
      - name: kcp-certs
        secret:
          secretName: kcp-secret
      - name: kcp-config
        configMap:
          name: kcp-config
